(define (problem strips-gripper-custom)
   (:domain gripper-strips)
   (:objects rooma roomb ball1 left)
   (:init (room rooma)
          (room roomb)
          (ball ball1)
          (at-robby rooma)
          (free left)
          (at ball1 rooma)
          (gripper left))
   (:goal (and (at ball1 roomb))))